config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  root to: "users#home"
  resources :hotels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
	belongs_to :sender, :foreign_key => "sender_id", :class_name => 'User'
	belongs_to :hotel
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	validates :title, :address, presence: true
	has_many :feedbacks
	mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_feedbacks, :class_name => 'Feedback', :foreign_key => 'sender_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    current_user_path
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def index
    @feedback = Feedback.all
  end

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(feedback_params)
      respond_to do |format|
      if @feedback.save
         format.html { redirect_to hotel_path, notice: ' Feedback was successfully created.' }
      else
        format.html { redirect_to hotel_path, notice: ' something wrong.' }
       end
      end
  end

  def show
    @feedback = Feedback.find(params[:id])
  end

  private
  def feedback_params
    params.require(:feedback).permit(:id, :user_name, :sender_id, :body)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  def index
    @hotels = Hotel.all
    @feedbacks = Feedback.all
  end

	def new
		@hotel = Hotel.new
    @feedback = Feedback.new
	end

	def create
      @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to hotels_path
    else
      render "new"
    end
  end

  def show
  	@hotel = Hotel.find(params[:id])
  end

  private

    def hotel_params
    	params.require(:hotel).permit(:id, :title, :breakfast, :room_description, :price, 
                                     :address, :photo)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @feedbacks = Feedback.all
  end

  def new
	@feedback = Feedback.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/hotels/index.html.haml
- @hotels.each  do |hotel|
  - if hotel.photo.present?
    = image_tag(hotel.photo_url(:thumb))
  %p
    = hotel.id
  %p
    = hotel.title
  %p
    = hotel.address
  %p
    = hotel.room_description
  %p
    = hotel.price
  %p
    - case hotel.breakfast 
      - when true
        %p Breakfast included
      - else
        %p No breakfast
        

app/views/hotels/new.html.haml
.row
  .box
    .col-lg-12
      %hr/
      %h2.intro-text.text-center
        %strong New Hotel
      %hr/
    .col-md-12
      = simple_form_for @hotel, html: { class: 'form-horizontal'} do |f|
        = f.error_notification
        = f.label :title
        = f.text_field :title, required: false, class: 'form-control', autofocus: true
        = f.input :address, :placeholder => "e.g. City, Country", input_html: { id: 'geocomplete_country'}, class: 'form-control', autofocus: true, id: "close-form"
        = f.label :room_description
        = f.text_area :room_description, required: false, class: 'form-control', autofocus: true
        = f.label :price
        = f.text_field :price, required: false, class: 'form-control', autofocus: true
        = f.label :breakfast
        = f.check_box :breakfast, include_hidden: true
        = f.file_field :photo

        .actions
          = f.submit "Save",  class: "btn btn-default"

app/views/hotels/show.html.haml
.row
  .col-md-4
    .user_logo
      - if @hotel.photo.present?
        = image_tag(@hotel.photo_url(:thumb))
  .col-md-4
    %p #{@hotel.title}
    %p #{@hotel.address}
    %p #{@hotel.room_description}
    %p #{@hotel.price}
    - case @hotel.breakfast 
      - when true
        %p Breakfast included
      - else
        %p Without breakfast
/ .row
/   %h4 Feedbacks:
/   - @hotel.feedbacks.each do |feedback|
/     %p
/       %strong User name:
/       = feedback.sender.user_name
/     %p
/       %strong Feedback:
/       = feedback.body
/   %h4 Add a feedback:
/   = simple_form_for(@feedbacks) do |f|
/     %p
/       %strong User name
/       %br
/         = f.text_field :user_name
/         = f.hidden_field :sender_id, value: current_user.id
/     %p
/       = f.label :body
/       %br
/         = f.text_area :body
/     %p
/       = f.submit
/   = link_to 'Edit', edit_hotel_path(@hotel)
/   |
/   \#{link_to 'Back', hotels_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Vacation
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places", :type => "text/javascript"}
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :integrity => "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", :rel => "stylesheet"}/
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css", :integrity => "sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Spirax", :rel => "stylesheet"}/

  %body
    = render "users/header"
    = yield

app/views/users/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.navbar-brand.name-of-the-project{:href => "#"} your perfect vacation
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "#"} Home
        %li
          %a{:href => "#about"} About
        %li
          %a{:href => "#contact"} Contact
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "hotels/index"} Hotels
        %li
          %a{:href => "../navbar-static-top/"} Static top
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              My account
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "hotels/new"} Add hotel
              %li.divider{:role => "separator"}
              %li
                = link_to "Sign out", destroy_user_session_path, :method=>'delete'
        - else
          %li
            = link_to "Sign in", new_user_session_path


    / /.nav-collapse